# Python package

trigger:
- main
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'quantumtrio-service-connection'
    appType: 'webApp'
    appName: 'quantumtrio-service-connection'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
