"""Add unique constraint to departament_manager column

Revision ID: aebf36ccd5cc
Revises: db225219b5fc
Create Date: 2024-03-02 14:23:57.557569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebf36ccd5cc'
down_revision: Union[str, None] = 'db225219b5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departaments', ['departament_manager'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departaments', type_='unique')
    # ### end Alembic commands ###
