"""remodify_departament_table

Revision ID: db225219b5fc
Revises: 382dca74843b
Create Date: 2024-03-01 18:16:44.452421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db225219b5fc'
down_revision: Union[str, None] = '382dca74843b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departaments', sa.Column('departament_manager', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departaments', 'users', ['departament_manager'], ['id'])
    op.drop_column('departaments', 'departament_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departaments', sa.Column('departament_admin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'departaments', type_='foreignkey')
    op.drop_column('departaments', 'departament_manager')
    # ### end Alembic commands ###
